events {}

http {
    include mime.types;

    server {
        listen 80;

        location /static/ {
            alias /app/static/;
        }

        location / {
            auth_basic "Restricted Area";
            auth_basic_user_file /etc/nginx/conf.d/auth;
            proxy_pass http://telegram-bot:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
