apiVersion: v1
kind: ConfigMap
metadata:
  name: fashion-config
data:
  POSTGRES_DB: "fashion_db"
  POSTGRES_USER: "fashion_user"
  DATABASE_URL: "postgresql://fashion_user:fashion_pass@db:5432/fashion_db"
  REDIS_URL: "redis://redis:6379/0"
  DEBUG: "False"