apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: postgres:15-alpine
          envFrom:
            - configMapRef:
                name: fashion-config
            - secretRef:
                name: fashion-secrets
          command:
            - /bin/sh
            - -c
            - |
              set -e

              echo "Ожидание запуска базы данных..."
              until PGPASSWORD="$POSTGRES_PASSWORD" pg_isready -h db -p 5432 -U "$POSTGRES_USER"; do
                sleep 2
              done

              echo "✅ База готова! Выполняем миграцию..."
              PGPASSWORD="$POSTGRES_PASSWORD" psql -h db -U "$POSTGRES_USER" -d "$POSTGRES_DB" -f /scripts/001_initial.sql

              echo "✅ Миграция успешно завершена!"
          volumeMounts:
            - name: script-volume
              mountPath: /scripts/001_initial.sql
              subPath: 001_initial.sql
      volumes:
        - name: script-volume
          configMap:
            name: db-migration-sql
