apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: fashion-bot:latest
          imagePullPolicy: IfNotPresent
          command: ["celery", "-A", "app.worker.celery_app.celery_app", "worker", "--loglevel=info", "--concurrency=2"]
          envFrom:
            - configMapRef:
                name: fashion-config
            - secretRef:
                name: fashion-secrets
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi" # После добавлении модели можно увеличить до 8
              cpu: "2"